# Generated by Django 4.2 on 2023-04-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Member",),
    ]
