# Generated by Django 4.2 on 2023-04-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_alter_member_subscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="subscription_plan",
            field=models.ForeignKey(
                default="Premium",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscription.subscriptionplan",
            ),
        ),
    ]
