# Generated by Django 4.2 on 2023-04-12 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("referral_code", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="default.jpeg", null=True, upload_to="profile_pics"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Select Gender", "Select Gender"),
                            ("Male", "Male"),
                            ("Female", "Female"),
                        ],
                        default="Select Gender",
                        max_length=30,
                    ),
                ),
                ("dob", models.DateField(null=True)),
                (
                    "phone_no",
                    models.CharField(
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="must be a valid phone number",
                                regex="^[0]\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(max_length=150, null=True)),
                ("lga", models.CharField(max_length=30, null=True)),
                ("state", models.CharField(max_length=30, null=True)),
                ("nationality", models.CharField(default="Nigerian", max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="accounts.customuser",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="accounts.customuser",
                    ),
                ),
            ],
            options={"unique_together": {("follower", "followed")},},
        ),
    ]
