# Generated by Django 4.2 on 2023-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referrer",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
