# Generated by Django 4.2 on 2023-04-13 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_referrer"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="referrer",),
        migrations.AddField(
            model_name="customuser",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
