# Generated by Django 4.2 on 2023-04-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_customuser_referrer_customuser_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="get_referral_code",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
