# Generated by Django 4.2 on 2023-04-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_get_referral_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="get_referral_code",
            new_name="any_referral_code",
        ),
    ]
