# Generated by Django 4.2 on 2023-04-13 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_get_referral_code_customuser_any_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 4, 13, 8, 55, 8, 680129, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
