# Generated by Django 4.2 on 2023-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(
                default="default.jpeg", null=True, upload_to="banner_pics"
            ),
        ),
    ]
