# Generated by Django 4.2 on 2023-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profile_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(default="", null=True, upload_to="banner_pics"),
        ),
    ]
