# Generated by Django 4.2 on 2023-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_profile_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(
                default="profile-bg.jpg", null=True, upload_to="banner_pics"
            ),
        ),
    ]
